### ISSUE TITLE
Build errors v2.0.0 on XCode 12.5 Beta

### ISSUE THREAD

**Issue by vsbirkhaug** [CombineCommunity/RxCombine#24]
Hi, you are missing some `@available iOS >13` in the latest release. I see you already have these changes in main, any chance of a new release including that? :)

**Comment by freak4pc** [comment]
Sure! I'll try to take care of it today.

**Comment by jtthrillson** [comment]
I opened a PR (#25) updating Package.swift to address this.

**Comment by freak4pc** [comment]
The right PR would be adding the missing availability statements, if you have the time

**Comment by jtthrillson** [comment]
I didn't read this issue closely enough. The changes have actually already been merged in commit 3b359e4901c383532a84d95094ad688fcb87a684. There just hasn't been a release since those changes were merged.

**Comment by laxmorek** [comment]
Hey @freak4pc @jtthrillson many thx for quick responses.

Unfortunately version `2.x` of the `RxCombine` requires the `RxSwift` in version `6.x`. A project I work on has to stay on the `RxSwift` in version `5.x` so I use the `RxCombine` in version `1.6.1`. 

Would be possible to release `1.6.2` version that contains this fix? It will allow me to stay with the `RxSwift` in version `5.x` and update the Xcode to version `12.5`.

**Comment by freak4pc** [comment]
Hey @laxmorek,
To be honest since it's not a very common use case I won't be able to find the time to cut this sort of a fix.

If you want to make a PR with the fixes on top of the 1.6.1 branch I'll do my best to help with everything related to cutting a release.

**Comment by darrarski** [comment]
@laxmorek @freak4pc I made a fork (based on `RxCombine` `1.6.1`), applied the fixes mentioned above, and bumped the version to `1.6.2`. You can use it in your project if you depend on `RxSwift` `5.x` and can't update to `6.x` yet. This way you can use `RxCombine` with `RxSwift` `5.x` and work on Xcode `>12.5`. Cheers 🍻

https://github.com/darrarski/RxCombine
