### ISSUE TITLE
watchOS deployment target too low

### ISSUE THREAD

**Issue by pbendersky** [CombineCommunity/RxCombine#30]
From Podspec:
`s.watchos.deployment_target = '3.0'`

However, Combine was introduced in watchOS 6, so in a standalone watchOS app, the library fails to compile.

**Comment by freak4pc** [comment]
Hey, 
There are compile time statements that don't compile this code below watchOS 6. 

The point is being able to bundle this in a watchOS app that might support an older deployment target but also uses some newer code in parallel.

**Comment by pbendersky** [comment]
it still failed to compile for us... I'll try to isolate it in a sample.
